services:
  - type: web
    name: skulxa
    runtime: go
    plan: free
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: ./h2apk
    envVars:
      - key: PORT
        value: 10000
      - key: RENDER_PROJECT_DIR
        value: /opt/render/project
